Fix/next 244
PaladinCloud/ce-extensions pull request #14
Opened 2024-10-10 23:41 UTC by plyubich

2024-10-11 17:14 UTC, kevin-paladin requested changes
There's a minor change I'd like to see; it all looks good

2024-10-11 17:14 UTC, kevin-paladin commented on ui-asset-management/api/svc-asset-details/extension/clients/secrets_client.go
> +		SecretId:     aws.String("paladincloud/secret/98c28482-9bae-46bd-bd4e-58fa132e72c0"),
Did you mean to replace the hard-coded string with `secretId` that was created a few lines above?

2024-10-11 18:32 UTC, kevin-paladin reviewed
Looks good!

2024-10-14 22:06 UTC, plyubich commented on ui-asset-management/api/svc-asset-details/extension/main_test.go
> +}
yes, implement this test

2024-10-14 22:07 UTC, kevin-paladin approved these changes

2024-10-14 22:07 UTC, merged